kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "postgres"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "15"
  numberOfInstances: 3
  enableMasterLoadBalancer: true
  enableReplicaLoadBalancer: true
  volume:
    size: "20Gi"
    storageClass: "longhorn"
  users:
    odoo:
    - superuser
    - createdb
    - createrole
    - replication
    - bypassrls
  allowedSourceRanges:
    # IP ranges to access your cluster go here

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
