apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: odoo-postgres
  namespace: odoo
spec:
  teamId: "odoo-team"
  volume:
    size: 10Gi
    storageClass: manual
  numberOfInstances: 3
  users:
    odoo_user:  # Database user
      - superuser
      - createdb
  databases:
    odoo_db: odoo_user  # Database name and owner
  postgresql:
    version: "15"
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  enableConnectionPooler: true
  connectionPooler:
    mode: session
    numberOfInstances: 2
