apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificateodoo
  namespace: odoo

spec:
  secretName: secret-tls
  renewBefore: 240h
  duration: 2160h
  commonName: odoo.app.devopsbr.com.br
  dnsNames:
  - odoo.app.devopsbr.com.br
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer