kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: odoo-pv-claim
  annotations:
     longhorn.io/replica-count: "3"
  labels:
    app: odoo
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi